name: CI Pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Permissions
        run: chmod +x hello.sh

      - name: Run Script
        run: ./hello.sh
